# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('price_wholesale', models.IntegerField()),
                ('price_retail', models.IntegerField()),
                ('producer', models.CharField(max_length=200)),
            ],
        ),
    ]
